### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mikhoul** [CodeDead/MemPlus#4]
Could you make the popup at the end optional ? 

Regards :octocat:

**Comment by CodeDead** [comment]
Already fixed ;)
https://github.com/CodeDead/MemPlus/commit/a839fd88892719278973078a110ce45a5b0b5f80

**Comment by CodeDead** [comment]
New release out now, which includes this feature:
https://github.com/CodeDead/MemPlus/releases/tag/1.1
